name: farmapp
description: "Farmapp"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  http: ^1.2.1
  change_app_package_name: ^1.1.0
  pie_chart: ^5.4.0
  rflutter_alert: ^2.0.7
  pdf: ^3.10.8
  flutter_launcher_icons: ^0.13.1
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icono.png"
  web:
    generate: true
    image_path: "assets/icon/icono.png"
  windows:
    generate: true
    image_path: "assets/icon/icono.png"

flutter:
  uses-material-design: true